CUDA_VISIBLE_DEVICES=1 nohup python ../../main/__main__.py --seed=0 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

CUDA_VISIBLE_DEVICES=2 nohup python ../../main/__main__.py --seed=1 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=2 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=3 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=4 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=5 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=6 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=7 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=8 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

# CUDA_VISIBLE_DEVICES=3 nohup python ../../main/__main__.py --seed=9 --fn=../../datasets/LastFM_final_v3_0.5 --alg=GraConUCB --staU=0 --endU=1000 --attrPolicy=Gopt-Pro --GF=Y --similarity=hop-tanimoto+cos --k=1 --useSumOuter=Y --cos_lambda=0.7 --TV=1.7 --armRelation=arm_suparm_relation_plain --RMRho=0.1 --RSetting=1 --blackList=Kt_stat_[Gopt-Pro_gfN_1-hop-tanimoto+cos_SumOuter_0.15C_0.7CosGamma_TV1.7_user_item_test].json &

